- name: Preparing Workstation
  hosts: localhost
  become: true
  connection: local
  tasks:

  - name: Installing Linux Apps
    apt:
      name: '{{ item }}'
      install_recommends: yes
      state: present
    loop:
    - vim
    - htop
    - curl
    - wget
    - ncdu
    - apt-transport-https
    - ca-certificates
    - gnupg
    - python3-pip
    - make
    - git
    - bash-completion
    - gdebi
    - gnupg-agent
    - color-picker
    - spotify-client
    - flameshot
    - fonts-hack
    - tilix
    - virtualbox
    - mlocate
    - jq
    - mtr

  - name: Installing Google Chrome
    block:
    - name: Baixar o pacote .deb do Google Chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb
    - name: Instalar o pacote do Google Chrome
      apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb
        state: present
    - name: Limpar o arquivo .deb após instalação
      file:
        path: /tmp/google-chrome-stable_current_amd64.deb
        state: absent

  - block:
    - name: Installing Winbox 4.0beta14
      unarchive:
        src: 'https://download.mikrotik.com/routeros/winbox/4.0beta14/WinBox_Linux.zip'
        dest: /usr/local/bin
        remote_src: yes

  - block:
    - name: Installing Vagrant 2.2.19
      unarchive:
        src: 'https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_linux_amd64.zip'
        dest: /usr/local/bin
        remote_src: yes

  - block:
    - name: Installing AWS CLI via pip3
      pip:
        name: awscli
        executable: pip3
