- name: Preparing workstation
  hosts: localhost
  become: true
  connection: local
  tasks:

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Linux apps
    apt:
      name: '{{ item }}'
      install_recommends: yes
      state: present
    loop:
    - apt-transport-https
    - bash-completion
    - ca-certificates
    - color-picker
    - curl
    - filezilla
    - flameshot
    - flatpak
    - fonts-hack
    - gdebi
    - git
    - gnupg
    - gnupg-agent
    - htop
    - jq
    - make
    - mlocate
    - mtr
    - ncdu
    - network-manager-l2tp
    - network-manager-l2tp-gnome
    - neofetch
    - nmap
    - openssh-client
    - openssh-server
    - python3-pip
    - spotify-client
    - steam
    - tilix
    - vim
    - virtualbox
    - vlc
    - wget
    - xl2tpd
    - xrdp

  - name: Set alias preferences
    lineinfile:
      path: /etc/bash.bashrc
      line: "{{ item }}"
      state: present
    loop:
    - 'alias inet="ip -br -c a"'
    - 'alias dt="date +%H:%M"'
    - 'alias k=kubectl'

  - name: Configure vim settings
    blockinfile:
      path: /etc/vim/vimrc
      block: |
        set expandtab
        set tabstop=2
        set shiftwidth=2

  - name: Configure neofetch to run at terminal startup
    lineinfile:
      path: ~/.bashrc
      line: 'neofetch'
      state: present

  - name: Customize neofetch settings
    blockinfile:
      path: ~/.config/neofetch/config.conf
      create: yes
      block: |
        print_info() {
            info title
            info underline
            info "OS"
            info "Host"
            info "Kernel"
            info "Uptime"
            info "Packages"
            info "Shell"
            info "Resolution"
            info "DE"
            info "WM"
            info "Terminal"
            info "CPU"
            info "Memory"
        }

  - name: Install balenaEtcher
    get_url:
      url: 'https://github.com/balena-io/etcher/releases/download/v1.19.25/balenaEtcher-1.19.25-x64.AppImage'
      dest: /usr/local/bin/balena
      mode: '0755'

  - name: Install Google Chrome
    block:
    - name: Download Google Chrome .deb package
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb
    - name: Install Google Chrome package
      apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb
        state: present
    - name: Remove Google Chrome .deb package
      file:
        path: /tmp/google-chrome-stable_current_amd64.deb
        state: absent

  - name: Install Winbox 4.0beta14
    unarchive:
      src: 'https://download.mikrotik.com/routeros/winbox/4.0beta14/WinBox_Linux.zip'
      dest: /usr/local/bin
      remote_src: yes

  - name: Install Vagrant 2.2.19
    unarchive:
      src: 'https://releases.hashicorp.com/vagrant/2.4.3/vagrant_2.4.3_linux_amd64.zip'
      dest: /usr/local/bin
      remote_src: yes

  - name: Install AWS CLI via pip3
    pip:
      name: awscli
      executable: pip3

  - name: Add vscode repository key
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - name: Add vscode repository
    apt_repository:
      repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
      state: present
  - name: Install vscode
    apt:
      name: code
      state: present
  - name: Install vscode extensions
    become: false
    shell: code --install-extension {{ item }} --no-sandbox --user-data-dir=/home/$USER/.vscode
    loop:
    - bbenoist.vagrant
    - dracula-theme.theme-dracula
    - bceskavich.theme-dracula-at-night
    - equinusocio.vsc-material-theme-icons
    - foxundermoon.shell-format
    - hashicorp.terraform
    - kennylong.kubernetes-yaml-formatter
    - ms-azuretools.vscode-docker
    - ms-python.autopep8
    - ms-python.python
    - njpwerner.autodocstring
    - Postman.postman-for-vscode
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-portuguese
    - zhuangtongfa.Material-theme

  - name: Import Ulauncher GPG key
    command: gpg --keyserver keyserver.ubuntu.com --recv-keys 0xFAF1020699503176
    args:
      creates: /root/.gnupg/pubring.kbx
  - name: Export Ulauncher GPG key to keyring
    command: gpg --export 0xFAF1020699503176
    register: gpg_key
  - name: Save Ulauncher GPG key to keyring
    copy:
      content: "{{ gpg_key.stdout }}"
      dest: /usr/share/keyrings/ulauncher-archive-keyring.gpg
  - name: Add Ulauncher repository
    copy:
      content: "deb [signed-by=/usr/share/keyrings/ulauncher-archive-keyring.gpg] http://ppa.launchpad.net/agornostal/ulauncher/ubuntu jammy main\n"
      dest: /etc/apt/sources.list.d/ulauncher-jammy.list
  - name: Update apt cache
    apt:
      update_cache: yes
  - name: Install Ulauncher
    apt:
      name: ulauncher
      state: present

  - name: Add Flathub repository
    shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    args:
      creates: /var/lib/flatpak/repo/flathub.flatpakrepo
  - name: Install applications via flatpak
    shell: flatpak install -y flathub {{ item }}
    args:
      creates: /var/lib/flatpak/app/{{ item }}
    loop:
    - com.bitwarden.desktop
    - com.discordapp.Discord
    - com.github.unrud.VideoDownloader
    - com.obsproject.Studio
    - org.qbittorrent.qBittorrent
    - org.telegram.desktop
