- name: Preparing workstation
  hosts: localhost
  become: true
  connection: local
  tasks:

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Linux apps
    apt:
      name: '{{ item }}'
      install_recommends: yes
      state: present
    loop:
    - apt-transport-https
    - bash-completion
    - ca-certificates
    - curl
    - flameshot
    - fonts-hack
    - gdebi
    - git
    - gnupg
    - gnupg-agent
    - htop
    - jq
    - make
    - mlocate
    - mtr
    - ncdu
    - network-manager-l2tp
    - network-manager-l2tp-gnome
    - neofetch
    - python3-pip
    - tilix
    - vim
    - virtualbox
    - wget

  - name: Set alias preferences
    lineinfile:
      path: /etc/bash.bashrc
      line: "{{ item }}"
      state: present
    loop:
    - 'alias inet="ip -br -c a"'
    - 'alias dt="date +%H:%M"'
    - 'alias k=kubectl'

  - name: Configure vim settings
    blockinfile:
      path: /etc/vim/vimrc
      block: |
        set expandtab
        set tabstop=2
        set shiftwidth=2

  - name: Configure neofetch to run at terminal startup
    lineinfile:
      path: ~/.bashrc
      line: 'neofetch'
      state: present

  - name: Customize neofetch settings
    blockinfile:
      path: ~/.config/neofetch/config.conf
      create: yes
      block: |
        print_info() {
            info title
            info underline
            info "OS"
            info "Host"
            info "Kernel"
            info "Uptime"
            info "Packages"
            info "Shell"
            info "Resolution"
            info "DE"
            info "WM"
            info "Terminal"
            info "CPU"
            info "Memory"
        }

  - name: Install Google Chrome
    block:
    - name: Download Google Chrome .deb package
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb
    - name: Install Google Chrome package
      apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb
        state: present
    - name: Remove Google Chrome .deb package
      file:
        path: /tmp/google-chrome-stable_current_amd64.deb
        state: absent

  - name: Install Winbox 4.0beta14
    unarchive:
      src: 'https://download.mikrotik.com/routeros/winbox/4.0beta14/WinBox_Linux.zip'
      dest: /usr/local/bin
      remote_src: yes

  - name: Install Vagrant 2.2.19
    unarchive:
      src: 'https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_linux_amd64.zip'
      dest: /usr/local/bin
      remote_src: yes

  - name: Install AWS CLI via pip3
    pip:
      name: awscli
      executable: pip3

  - name: Add vscode repository key
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - name: Add vscode repository
    apt_repository:
      repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
      state: present
  - name: Install vscode
    apt:
      name: code
      state: present
  - name: Install vscode extensions
    become: false
    shell: code --install-extension {{ item }} --no-sandbox --user-data-dir=/home/$USER/.vscode
    loop:
    - bbenoist.vagrant
    - dracula-theme.theme-dracula
    - bceskavich.theme-dracula-at-night
    - equinusocio.vsc-material-theme-icons
    - foxundermoon.shell-format
    - hashicorp.terraform
    - kennylong.kubernetes-yaml-formatter
    - ms-azuretools.vscode-docker
    - ms-python.autopep8
    - ms-python.python
    - njpwerner.autodocstring
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-portuguese
