- name: Preparing workstation
  hosts: localhost
  become: true
  connection: local
  tasks:

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Linux apps
    apt:
      name: '{{ item }}'
      install_recommends: yes
      state: present
    loop:
    - apt-transport-https
    - bash-completion
    - ca-certificates
    - color-picker
    - curl
    - filezilla
    - flameshot
    - flatpak
    - fonts-hack
    - gdebi
    - git
    - gnupg
    - gnupg-agent
    - htop
    - jq
    - make
    - mlocate
    - mtr
    - ncdu
    - network-manager-l2tp
    - network-manager-l2tp-gnome
    - neofetch
    - nmap
    - openssh-client
    - openssh-server
    - python3-pip
    - steam
    - tilix
    - vim
    - virtualbox
    - vlc
    - wget
    - xl2tpd
    - xrdp

  - name: Set alias preferences
    lineinfile:
      path: /etc/bash.bashrc
      line: "{{ item }}"
      state: present
    loop:
    - 'alias inet="ip -br -c a"'
    - 'alias dt="date +%H:%M"'
    - 'alias k=kubectl'
    - 'source <(kubectl completion bash)'
    - 'complete -o default -F __start_kubectl k'

  - name: Configure vim settings
    blockinfile:
      path: /etc/vim/vimrc
      block: |
        set expandtab
        set tabstop=2
        set shiftwidth=2
      marker: "# {mark} default block"

  - name: Configure neofetch to run at terminal startup
    lineinfile:
      path: ~/.bashrc
      line: 'neofetch'
      state: present

  - name: Customize neofetch settings
    blockinfile:
      path: ~/.config/neofetch/config.conf
      create: yes
      block: |
        print_info() {
            info title
            info underline
            info "OS"
            info "Host"
            info "Kernel"
            info "Uptime"
            info "Packages"
            info "Shell"
            info "Resolution"
            info "DE"
            info "WM"
            info "Terminal"
            info "CPU"
            info "Memory"
        }

  - name: Install balenaEtcher
    get_url:
      url: 'https://github.com/balena-io/etcher/releases/download/v1.19.25/balenaEtcher-1.19.25-x64.AppImage'
      dest: /usr/local/bin/balena
      mode: '0755'

  - name: Download Tor Browser
    get_url:
      url: https://dist.torproject.org/torbrowser/14.0.3/tor-browser-linux-x86_64-14.0.3.tar.xz
      dest: "/opt/tor-browser.tar.xz"
      mode: '0644'
      validate_certs: no
  - name: Extract Tor Browser
    unarchive:
      src: "/opt/tor-browser.tar.xz"
      dest: "/opt"
      remote_src: yes
      mode: '0644'
  - name: Change ownership and permissions of Tor Browser directory
    file:
      path: "/opt/tor-browser"
      owner: "{{ lookup('env', 'USER') }}"
      group: "{{ lookup('env', 'USER') }}"
      mode: '0755'
      recurse: yes
  - name: Make the startup script executable
    file:
      path: "/opt/tor-browser/start-tor-browser.desktop"
      mode: '0755'
  - name: Register Tor Browser as an application
    shell: "cd /opt/tor-browser && ./start-tor-browser.desktop --register-app"
    become: false
    become_user: "{{ lookup('env', 'USER') }}"
    args:
      creates: "{{ lookup('env', 'HOME') }}/.local/share/applications/start-tor-browser.desktop"
  - name: Create symbolic link for Tor Browser
    file:
      src: "/opt/tor-browser/Browser/start-tor-browser"
      dest: "/usr/local/bin/tor"
      state: link

  - name: Download and install Google Chrome GPG key
    apt_key:
      url: https://dl.google.com/linux/linux_signing_key.pub
      state: present
  - name: Add Google Chrome repository
    apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] https://dl.google.com/linux/chrome/deb/ stable main"
      state: present
      filename: google-chrome
  - name: Update apt cache
    apt:
      update_cache: yes
  - name: Install Google Chrome
    apt:
      name: google-chrome-stable
      state: present

  - name: Install Winbox 4.0beta14
    unarchive:
      src: 'https://download.mikrotik.com/routeros/winbox/4.0beta14/WinBox_Linux.zip'
      dest: /usr/local/bin
      remote_src: yes
  - name: Create symbolic link for Winbox 4.0beta14
    file:
      src: /usr/local/bin/WinBox
      dest: /usr/local/bin/winbox
      state: link

  - name: Install Vagrant 2.2.19
    unarchive:
      src: 'https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_linux_amd64.zip'
      dest: /usr/local/bin
      remote_src: yes

  - name: Install AWS CLI via pip3
    pip:
      name: awscli
      executable: pip3

  - name: Download and install vscode GPG key
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - name: Add vscode repository
    apt_repository:
      repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
      state: present
  - name: Update apt cache
    apt:
      update_cache: yes
  - name: Install vscode
    apt:
      name: code
      state: present
  - name: Install vscode extensions
    become: false
    shell: code --install-extension {{ item }} --no-sandbox --user-data-dir=/home/$USER/.vscode
    loop:
    - bbenoist.vagrant
    - dracula-theme.theme-dracula
    - bceskavich.theme-dracula-at-night
    - equinusocio.vsc-material-theme-icons
    - foxundermoon.shell-format
    - hashicorp.terraform
    - kennylong.kubernetes-yaml-formatter
    - ms-azuretools.vscode-docker
    - ms-python.autopep8
    - ms-python.python
    - njpwerner.autodocstring
    - Postman.postman-for-vscode
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-portuguese
    - zhuangtongfa.Material-theme

  - name: Import Ulauncher GPG key
    command: gpg --keyserver keyserver.ubuntu.com --recv-keys 0xFAF1020699503176
    args:
      creates: /root/.gnupg/pubring.kbx
  - name: Export Ulauncher GPG key to keyring
    command: gpg --export 0xFAF1020699503176
    register: gpg_key
  - name: Save Ulauncher GPG key to keyring
    copy:
      content: "{{ gpg_key.stdout }}"
      dest: /usr/share/keyrings/ulauncher-archive-keyring.gpg
  - name: Add Ulauncher repository
    copy:
      content: "deb [signed-by=/usr/share/keyrings/ulauncher-archive-keyring.gpg] http://ppa.launchpad.net/agornostal/ulauncher/ubuntu jammy main\n"
      dest: /etc/apt/sources.list.d/ulauncher-jammy.list
  - name: Update apt cache
    apt:
      update_cache: yes
  - name: Install Ulauncher
    apt:
      name: ulauncher
      state: present

  - name: Add Flathub repository
    shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    args:
      creates: /var/lib/flatpak/repo/flathub.flatpakrepo
  - name: Install applications via flatpak
    shell: flatpak install -y flathub {{ item }}
    args:
      creates: /var/lib/flatpak/app/{{ item }}
    loop:
    - com.bitwarden.desktop
    - com.discordapp.Discord
    - com.github.unrud.VideoDownloader
    - com.obsproject.Studio
    - com.spotify.Client
    - org.qbittorrent.qBittorrent
    - org.telegram.desktop

  - name: Download Docker installation script
    get_url:
      url: https://get.docker.com
      dest: /tmp/get-docker.sh
      mode: '0755'
  - name: Install Docker
    shell: sh /tmp/get-docker.sh
    args:
      creates: /usr/bin/docker
  - name: Start and enable Docker services
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
    - docker.socket
    - docker.service
  - name: Add user to docker group
    user:
      name: "{{ lookup('env', 'USER') }}"
      groups: docker
      append: yes
  - name: Display message
    debug:
      msg:
      - "Instalação e configuração concluídas com sucesso! =D"
      - "Execute 'newgrp docker' para aplicar as mudanças de grupo"

  - name: Install Docker Compose
    get_url:
      url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
      dest: /usr/local/bin/docker-compose
      mode: '0755'

  - name: Install Kind
    get_url:
      url: https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
      dest: /usr/local/bin/kind
      mode: '0755'

  - name: Install kubectl
    get_url:
      url: "https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl"
      dest: /usr/local/bin/kubectl
      mode: '0755'
